on: push
name: FTP Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Ensure out directory exists
      run: mkdir -p out

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: Debug Build Directory
      run: ls -la out/

    # - name: 📂 Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USER_NAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: out/
    #     server-dir: /

    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USER_NAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "out/"
        remoteDir: "/"
        options: "--delete --asci"        