on: push
name: FTP Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔨 Build Project
        run: |
          cd hello-next
          npm install
          npm run build

      - name: 📂 Upload via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "hello-next/out/"
          remoteDir: "/"
          options: "--delete --asci"